# Generated by Django 4.1.4 on 2023-01-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_type_clothing_remove_clothes_publication_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gender',
            table='Generos',
        ),
    ]
