# Generated by Django 4.1.4 on 2023-01-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_gender_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gender',
            table=None,
        ),
    ]
