# Generated by Django 4.1.4 on 2023-01-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_alter_gender_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gender',
            table='Generos',
        ),
        migrations.AlterModelTable(
            name='type_clothing',
            table='Tipo de prenda',
        ),
    ]
