# Generated by Django 4.1.4 on 2023-01-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_alter_gender_table_alter_type_clothing_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clothes',
            table='Prendas',
        ),
    ]
