# Generated by Django 4.1.4 on 2023-01-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_alter_clothes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clothes',
            table='Clothes',
        ),
        migrations.AlterModelTable(
            name='gender',
            table='Genders',
        ),
        migrations.AlterModelTable(
            name='type_clothing',
            table='Type of clothing',
        ),
    ]
