# Generated by Django 4.1.4 on 2023-01-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_alter_type_clothing_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Clothes', 'verbose_name_plural': 'Clothes'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Gender', 'verbose_name_plural': 'Genders'},
        ),
        migrations.AlterModelOptions(
            name='type_clothing',
            options={'verbose_name': 'Type of clothes', 'verbose_name_plural': 'Type of clothes'},
        ),
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.type_clothing', verbose_name='Tipo de prenda'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.gender', verbose_name='Genero de la prenda'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='new_clothing',
            field=models.BooleanField(verbose_name='Prenda nueva'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='genders',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='type_clothing',
            name='categories',
            field=models.CharField(max_length=30),
        ),
    ]
