# Generated by Django 4.1.4 on 2023-01-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_rename_stock_clothes_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
