# Generated by Django 4.1.4 on 2023-01-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_clothes_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='is_sold',
        ),
    ]
