# Generated by Django 4.1.4 on 2023-01-27 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_remove_payment_cloth'),
        ('clothes', '0013_remove_clothes_is_paid_remove_clothes_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.payment', verbose_name='Medio de pago'),
        ),
    ]
