# Generated by Django 4.1.4 on 2023-01-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0014_clothes_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='client',
            field=models.CharField(max_length=20, null=True, verbose_name='Comprador'),
        ),
    ]
