# Generated by Django 4.1.4 on 2023-01-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0015_clothes_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='genders',
            field=models.CharField(max_length=10, null=True, verbose_name='Genero de la prenda'),
        ),
        migrations.AlterField(
            model_name='type_clothing',
            name='categories',
            field=models.CharField(max_length=30, verbose_name='Categoria de la prenda'),
        ),
    ]
