# Generated by Django 4.1.4 on 2023-01-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0016_alter_gender_genders_alter_type_clothing_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='client',
            new_name='client_username',
        ),
    ]
