# Generated by Django 4.1.4 on 2023-01-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0017_rename_client_clothes_client_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='client_username',
            new_name='buyer_username',
        ),
    ]
