# Generated by Django 4.1.4 on 2023-02-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0019_clothes_cloth_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='seller_username',
            field=models.CharField(max_length=20, null=True, verbose_name='Usuario del vendedor'),
        ),
    ]
