# Generated by Django 4.1.4 on 2023-02-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0020_clothes_seller_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.CharField(max_length=50, null=True, verbose_name='Talle de la prenda'),
        ),
    ]
