# Generated by Django 4.1.4 on 2023-01-10 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0009_alter_clothes_options_alter_gender_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100, verbose_name='Cliente')),
                ('clothes_name', models.CharField(max_length=100, verbose_name='Prenda')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creacion de la orden')),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=10, verbose_name='Metodo de pago')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.type_clothing', verbose_name='Categoria de la prenda')),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales',
                'db_table': 'Sales',
            },
        ),
    ]
