# Generated by Django 4.1.4 on 2023-01-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_rename_name_clothing_sales_cloth_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='cloth_id',
            new_name='cloth',
        ),
    ]
