# Generated by Django 4.1.4 on 2023-01-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_sales_cloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='cloth',
            field=models.IntegerField(verbose_name='Prenda a comprar'),
        ),
    ]
