# Generated by Django 4.1.4 on 2023-01-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_sales_cloth'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
