# Generated by Django 4.1.4 on 2023-01-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_sales_is_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
