# Generated by Django 4.1.4 on 2023-01-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_payment_cloth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cloth',
        ),
    ]
